apiVersion: v1
kind: Service
metadata:
  name: go-web
spec:
  type: NodePort # 在节点上部署访问 pod 的端口
  ports:
    - port: 8080 # service暴露在cluster上的端口，通过<cluster ip>:port访问服务，通过此端口集群内的服务可以互相访问
      targetPort: 8080 # pod的外部访问端口，port和nodePort的数据通过这个端口进入到Pod内部，Pod里面的containers的端口映射到这个端口，提供服务
      # NodePort: 30001 # Node节点的端口，<nodeIP>:nodePort 是提供给集群外部客户访问service的入口
      protocol: TCP
      name: http
  selector: # 匹配pod
    app: go-web
